### ISSUE TITLE
connection

### ISSUE THREAD

**Issue by abdoulayegk** [Ewonye/Ewonye#1]
I hope you're doing well. I would like to connect with you on LinkedIn or Twitter  you can follow me on : @abdoulayegk or click this link: https://www.linkedin.com/in/abdoulaye-balde-450152128/

**Comment by Ewonye** [comment]
Hello Abdoulaye Balde, hope you are well?
I have already connected with you on linkedin . Below is the link to my
profile.
https://www.linkedin.com/in/yakubu-ewonye-khadija-0b6225177/
